### ISSUE TITLE
Add ansible provisioner

### ISSUE THREAD

**Issue by stereohorse** [samoxbal/ansible-mesos-marathon-cluster#4]
1. Add ansible
2. Install Oracle JRE 8 with ansible on all vms

**Comment by samoxbal** [comment]
https://github.com/samoxbal/infrastructure/commit/900ea7d1c251e1d762059cbfdefa7851866861a8

**Comment by samoxbal** [comment]
https://github.com/samoxbal/infrastructure/commit/85f84ba6ac7785c26189614da725f6dd6354c53d
add info about start and provision

**Comment by samoxbal** [comment]
https://github.com/samoxbal/infrastructure/commit/40af882c5b2927d121076894878921dd4b68e723
maybe that?
