### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by stereohorse** [samoxbal/ansible-mesos-marathon-cluster#7]
`vm.box` and `memory` are duplicated in vms. Is there any way to deal with it? :)

**Comment by samoxbal** [comment]
https://github.com/samoxbal/infrastructure/commit/40743776efba821a25f4eeb44d6d3f4848fad7a2
maybe that?

**Comment by samoxbal** [comment]
https://github.com/samoxbal/infrastructure/commit/b4757e46893584c586a9a380695ae6c9cff57144
